environment:
  RUST_BACKTRACE: 1
  matrix:
    - TARGET: x86_64-pc-windows-gnu
      MSYS2_BITS: 64
    - TARGET: x86_64-pc-windows-msvc

install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
  - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - if defined MSYS2_BITS set PATH=%PATH%;C:\msys64\mingw%MSYS2_BITS%\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo test
